/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HackathonImport } from './routes/$hackathon'
import { Route as IndexImport } from './routes/index'
import { Route as HackathonIndexImport } from './routes/$hackathon/index'
import { Route as HackathonAuthImport } from './routes/$hackathon/_auth'
import { Route as HackathonAuthProfileImport } from './routes/$hackathon/_auth/profile'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HackathonRoute = HackathonImport.update({
  id: '/$hackathon',
  path: '/$hackathon',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HackathonIndexRoute = HackathonIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonAuthRoute = HackathonAuthImport.update({
  id: '/_auth',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonAuthProfileRoute = HackathonAuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HackathonAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$hackathon': {
      id: '/$hackathon'
      path: '/$hackathon'
      fullPath: '/$hackathon'
      preLoaderRoute: typeof HackathonImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$hackathon/_auth': {
      id: '/$hackathon/_auth'
      path: ''
      fullPath: '/$hackathon'
      preLoaderRoute: typeof HackathonAuthImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/': {
      id: '/$hackathon/'
      path: '/'
      fullPath: '/$hackathon/'
      preLoaderRoute: typeof HackathonIndexImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/_auth/profile': {
      id: '/$hackathon/_auth/profile'
      path: '/profile'
      fullPath: '/$hackathon/profile'
      preLoaderRoute: typeof HackathonAuthProfileImport
      parentRoute: typeof HackathonAuthImport
    }
  }
}

// Create and export the route tree

interface HackathonAuthRouteChildren {
  HackathonAuthProfileRoute: typeof HackathonAuthProfileRoute
}

const HackathonAuthRouteChildren: HackathonAuthRouteChildren = {
  HackathonAuthProfileRoute: HackathonAuthProfileRoute,
}

const HackathonAuthRouteWithChildren = HackathonAuthRoute._addFileChildren(
  HackathonAuthRouteChildren,
)

interface HackathonRouteChildren {
  HackathonAuthRoute: typeof HackathonAuthRouteWithChildren
  HackathonIndexRoute: typeof HackathonIndexRoute
}

const HackathonRouteChildren: HackathonRouteChildren = {
  HackathonAuthRoute: HackathonAuthRouteWithChildren,
  HackathonIndexRoute: HackathonIndexRoute,
}

const HackathonRouteWithChildren = HackathonRoute._addFileChildren(
  HackathonRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$hackathon': typeof HackathonAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/$hackathon/': typeof HackathonIndexRoute
  '/$hackathon/profile': typeof HackathonAuthProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$hackathon': typeof HackathonIndexRoute
  '/$hackathon/profile': typeof HackathonAuthProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$hackathon': typeof HackathonRouteWithChildren
  '/login': typeof LoginRoute
  '/$hackathon/_auth': typeof HackathonAuthRouteWithChildren
  '/$hackathon/': typeof HackathonIndexRoute
  '/$hackathon/_auth/profile': typeof HackathonAuthProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$hackathon'
    | '/login'
    | '/$hackathon/'
    | '/$hackathon/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$hackathon' | '/$hackathon/profile'
  id:
    | '__root__'
    | '/'
    | '/$hackathon'
    | '/login'
    | '/$hackathon/_auth'
    | '/$hackathon/'
    | '/$hackathon/_auth/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HackathonRoute: typeof HackathonRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HackathonRoute: HackathonRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$hackathon",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$hackathon": {
      "filePath": "$hackathon.tsx",
      "children": [
        "/$hackathon/_auth",
        "/$hackathon/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$hackathon/_auth": {
      "filePath": "$hackathon/_auth.tsx",
      "parent": "/$hackathon",
      "children": [
        "/$hackathon/_auth/profile"
      ]
    },
    "/$hackathon/": {
      "filePath": "$hackathon/index.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/_auth/profile": {
      "filePath": "$hackathon/_auth/profile.tsx",
      "parent": "/$hackathon/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
