/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HackathonImport } from './routes/$hackathon'
import { Route as IndexImport } from './routes/index'
import { Route as HackathonLoginImport } from './routes/$hackathon/login'
import { Route as HackathonAuthImport } from './routes/$hackathon/_auth'
import { Route as HackathonaccountIndexImport } from './routes/$hackathon/(account)/index'
import { Route as HackathoninformationVenueMapImport } from './routes/$hackathon/(information)/venue-map'
import { Route as HackathoninformationScheduleImport } from './routes/$hackathon/(information)/schedule'
import { Route as HackathoninformationHackerPackageImport } from './routes/$hackathon/(information)/hacker-package'
import { Route as HackathoninformationFaqsImport } from './routes/$hackathon/(information)/faqs'
import { Route as HackathonaccountSocialProfileImport } from './routes/$hackathon/(account)/social-profile'
import { Route as HackathonaccountRewardsImport } from './routes/$hackathon/(account)/rewards'
import { Route as HackathonAuthApplicationIndexImport } from './routes/$hackathon/_auth/application/index'
import { Route as HackathonAuthApplicationWelcomeImport } from './routes/$hackathon/_auth/application/welcome'
import { Route as HackathonAuthApplicationSkillsImport } from './routes/$hackathon/_auth/application/skills'
import { Route as HackathonAuthApplicationRsvpImport } from './routes/$hackathon/_auth/application/rsvp'
import { Route as HackathonAuthApplicationReviewImport } from './routes/$hackathon/_auth/application/review'
import { Route as HackathonAuthApplicationQuestionnaireImport } from './routes/$hackathon/_auth/application/questionnaire'
import { Route as HackathonAuthApplicationBasicInfoImport } from './routes/$hackathon/_auth/application/basic-info'

// Create/Update Routes

const HackathonRoute = HackathonImport.update({
  id: '/$hackathon',
  path: '/$hackathon',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HackathonLoginRoute = HackathonLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonAuthRoute = HackathonAuthImport.update({
  id: '/_auth',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonaccountIndexRoute = HackathonaccountIndexImport.update({
  id: '/(account)/',
  path: '/',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathoninformationVenueMapRoute =
  HackathoninformationVenueMapImport.update({
    id: '/(information)/venue-map',
    path: '/venue-map',
    getParentRoute: () => HackathonRoute,
  } as any)

const HackathoninformationScheduleRoute =
  HackathoninformationScheduleImport.update({
    id: '/(information)/schedule',
    path: '/schedule',
    getParentRoute: () => HackathonRoute,
  } as any)

const HackathoninformationHackerPackageRoute =
  HackathoninformationHackerPackageImport.update({
    id: '/(information)/hacker-package',
    path: '/hacker-package',
    getParentRoute: () => HackathonRoute,
  } as any)

const HackathoninformationFaqsRoute = HackathoninformationFaqsImport.update({
  id: '/(information)/faqs',
  path: '/faqs',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonaccountSocialProfileRoute =
  HackathonaccountSocialProfileImport.update({
    id: '/(account)/social-profile',
    path: '/social-profile',
    getParentRoute: () => HackathonRoute,
  } as any)

const HackathonaccountRewardsRoute = HackathonaccountRewardsImport.update({
  id: '/(account)/rewards',
  path: '/rewards',
  getParentRoute: () => HackathonRoute,
} as any)

const HackathonAuthApplicationIndexRoute =
  HackathonAuthApplicationIndexImport.update({
    id: '/application/',
    path: '/application/',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationWelcomeRoute =
  HackathonAuthApplicationWelcomeImport.update({
    id: '/application/welcome',
    path: '/application/welcome',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationSkillsRoute =
  HackathonAuthApplicationSkillsImport.update({
    id: '/application/skills',
    path: '/application/skills',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationRsvpRoute =
  HackathonAuthApplicationRsvpImport.update({
    id: '/application/rsvp',
    path: '/application/rsvp',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationReviewRoute =
  HackathonAuthApplicationReviewImport.update({
    id: '/application/review',
    path: '/application/review',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationQuestionnaireRoute =
  HackathonAuthApplicationQuestionnaireImport.update({
    id: '/application/questionnaire',
    path: '/application/questionnaire',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

const HackathonAuthApplicationBasicInfoRoute =
  HackathonAuthApplicationBasicInfoImport.update({
    id: '/application/basic-info',
    path: '/application/basic-info',
    getParentRoute: () => HackathonAuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$hackathon': {
      id: '/$hackathon'
      path: '/$hackathon'
      fullPath: '/$hackathon'
      preLoaderRoute: typeof HackathonImport
      parentRoute: typeof rootRoute
    }
    '/$hackathon/_auth': {
      id: '/$hackathon/_auth'
      path: ''
      fullPath: '/$hackathon'
      preLoaderRoute: typeof HackathonAuthImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/login': {
      id: '/$hackathon/login'
      path: '/login'
      fullPath: '/$hackathon/login'
      preLoaderRoute: typeof HackathonLoginImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(account)/rewards': {
      id: '/$hackathon/(account)/rewards'
      path: '/rewards'
      fullPath: '/$hackathon/rewards'
      preLoaderRoute: typeof HackathonaccountRewardsImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(account)/social-profile': {
      id: '/$hackathon/(account)/social-profile'
      path: '/social-profile'
      fullPath: '/$hackathon/social-profile'
      preLoaderRoute: typeof HackathonaccountSocialProfileImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(information)/faqs': {
      id: '/$hackathon/(information)/faqs'
      path: '/faqs'
      fullPath: '/$hackathon/faqs'
      preLoaderRoute: typeof HackathoninformationFaqsImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(information)/hacker-package': {
      id: '/$hackathon/(information)/hacker-package'
      path: '/hacker-package'
      fullPath: '/$hackathon/hacker-package'
      preLoaderRoute: typeof HackathoninformationHackerPackageImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(information)/schedule': {
      id: '/$hackathon/(information)/schedule'
      path: '/schedule'
      fullPath: '/$hackathon/schedule'
      preLoaderRoute: typeof HackathoninformationScheduleImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(information)/venue-map': {
      id: '/$hackathon/(information)/venue-map'
      path: '/venue-map'
      fullPath: '/$hackathon/venue-map'
      preLoaderRoute: typeof HackathoninformationVenueMapImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/(account)/': {
      id: '/$hackathon/(account)/'
      path: '/'
      fullPath: '/$hackathon/'
      preLoaderRoute: typeof HackathonaccountIndexImport
      parentRoute: typeof HackathonImport
    }
    '/$hackathon/_auth/application/basic-info': {
      id: '/$hackathon/_auth/application/basic-info'
      path: '/application/basic-info'
      fullPath: '/$hackathon/application/basic-info'
      preLoaderRoute: typeof HackathonAuthApplicationBasicInfoImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/questionnaire': {
      id: '/$hackathon/_auth/application/questionnaire'
      path: '/application/questionnaire'
      fullPath: '/$hackathon/application/questionnaire'
      preLoaderRoute: typeof HackathonAuthApplicationQuestionnaireImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/review': {
      id: '/$hackathon/_auth/application/review'
      path: '/application/review'
      fullPath: '/$hackathon/application/review'
      preLoaderRoute: typeof HackathonAuthApplicationReviewImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/rsvp': {
      id: '/$hackathon/_auth/application/rsvp'
      path: '/application/rsvp'
      fullPath: '/$hackathon/application/rsvp'
      preLoaderRoute: typeof HackathonAuthApplicationRsvpImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/skills': {
      id: '/$hackathon/_auth/application/skills'
      path: '/application/skills'
      fullPath: '/$hackathon/application/skills'
      preLoaderRoute: typeof HackathonAuthApplicationSkillsImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/welcome': {
      id: '/$hackathon/_auth/application/welcome'
      path: '/application/welcome'
      fullPath: '/$hackathon/application/welcome'
      preLoaderRoute: typeof HackathonAuthApplicationWelcomeImport
      parentRoute: typeof HackathonAuthImport
    }
    '/$hackathon/_auth/application/': {
      id: '/$hackathon/_auth/application/'
      path: '/application'
      fullPath: '/$hackathon/application'
      preLoaderRoute: typeof HackathonAuthApplicationIndexImport
      parentRoute: typeof HackathonAuthImport
    }
  }
}

// Create and export the route tree

interface HackathonAuthRouteChildren {
  HackathonAuthApplicationBasicInfoRoute: typeof HackathonAuthApplicationBasicInfoRoute
  HackathonAuthApplicationQuestionnaireRoute: typeof HackathonAuthApplicationQuestionnaireRoute
  HackathonAuthApplicationReviewRoute: typeof HackathonAuthApplicationReviewRoute
  HackathonAuthApplicationRsvpRoute: typeof HackathonAuthApplicationRsvpRoute
  HackathonAuthApplicationSkillsRoute: typeof HackathonAuthApplicationSkillsRoute
  HackathonAuthApplicationWelcomeRoute: typeof HackathonAuthApplicationWelcomeRoute
  HackathonAuthApplicationIndexRoute: typeof HackathonAuthApplicationIndexRoute
}

const HackathonAuthRouteChildren: HackathonAuthRouteChildren = {
  HackathonAuthApplicationBasicInfoRoute:
    HackathonAuthApplicationBasicInfoRoute,
  HackathonAuthApplicationQuestionnaireRoute:
    HackathonAuthApplicationQuestionnaireRoute,
  HackathonAuthApplicationReviewRoute: HackathonAuthApplicationReviewRoute,
  HackathonAuthApplicationRsvpRoute: HackathonAuthApplicationRsvpRoute,
  HackathonAuthApplicationSkillsRoute: HackathonAuthApplicationSkillsRoute,
  HackathonAuthApplicationWelcomeRoute: HackathonAuthApplicationWelcomeRoute,
  HackathonAuthApplicationIndexRoute: HackathonAuthApplicationIndexRoute,
}

const HackathonAuthRouteWithChildren = HackathonAuthRoute._addFileChildren(
  HackathonAuthRouteChildren,
)

interface HackathonRouteChildren {
  HackathonAuthRoute: typeof HackathonAuthRouteWithChildren
  HackathonLoginRoute: typeof HackathonLoginRoute
  HackathonaccountRewardsRoute: typeof HackathonaccountRewardsRoute
  HackathonaccountSocialProfileRoute: typeof HackathonaccountSocialProfileRoute
  HackathoninformationFaqsRoute: typeof HackathoninformationFaqsRoute
  HackathoninformationHackerPackageRoute: typeof HackathoninformationHackerPackageRoute
  HackathoninformationScheduleRoute: typeof HackathoninformationScheduleRoute
  HackathoninformationVenueMapRoute: typeof HackathoninformationVenueMapRoute
  HackathonaccountIndexRoute: typeof HackathonaccountIndexRoute
}

const HackathonRouteChildren: HackathonRouteChildren = {
  HackathonAuthRoute: HackathonAuthRouteWithChildren,
  HackathonLoginRoute: HackathonLoginRoute,
  HackathonaccountRewardsRoute: HackathonaccountRewardsRoute,
  HackathonaccountSocialProfileRoute: HackathonaccountSocialProfileRoute,
  HackathoninformationFaqsRoute: HackathoninformationFaqsRoute,
  HackathoninformationHackerPackageRoute:
    HackathoninformationHackerPackageRoute,
  HackathoninformationScheduleRoute: HackathoninformationScheduleRoute,
  HackathoninformationVenueMapRoute: HackathoninformationVenueMapRoute,
  HackathonaccountIndexRoute: HackathonaccountIndexRoute,
}

const HackathonRouteWithChildren = HackathonRoute._addFileChildren(
  HackathonRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$hackathon': typeof HackathonAuthRouteWithChildren
  '/$hackathon/login': typeof HackathonLoginRoute
  '/$hackathon/rewards': typeof HackathonaccountRewardsRoute
  '/$hackathon/social-profile': typeof HackathonaccountSocialProfileRoute
  '/$hackathon/faqs': typeof HackathoninformationFaqsRoute
  '/$hackathon/hacker-package': typeof HackathoninformationHackerPackageRoute
  '/$hackathon/schedule': typeof HackathoninformationScheduleRoute
  '/$hackathon/venue-map': typeof HackathoninformationVenueMapRoute
  '/$hackathon/': typeof HackathonaccountIndexRoute
  '/$hackathon/application/basic-info': typeof HackathonAuthApplicationBasicInfoRoute
  '/$hackathon/application/questionnaire': typeof HackathonAuthApplicationQuestionnaireRoute
  '/$hackathon/application/review': typeof HackathonAuthApplicationReviewRoute
  '/$hackathon/application/rsvp': typeof HackathonAuthApplicationRsvpRoute
  '/$hackathon/application/skills': typeof HackathonAuthApplicationSkillsRoute
  '/$hackathon/application/welcome': typeof HackathonAuthApplicationWelcomeRoute
  '/$hackathon/application': typeof HackathonAuthApplicationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$hackathon': typeof HackathonaccountIndexRoute
  '/$hackathon/login': typeof HackathonLoginRoute
  '/$hackathon/rewards': typeof HackathonaccountRewardsRoute
  '/$hackathon/social-profile': typeof HackathonaccountSocialProfileRoute
  '/$hackathon/faqs': typeof HackathoninformationFaqsRoute
  '/$hackathon/hacker-package': typeof HackathoninformationHackerPackageRoute
  '/$hackathon/schedule': typeof HackathoninformationScheduleRoute
  '/$hackathon/venue-map': typeof HackathoninformationVenueMapRoute
  '/$hackathon/application/basic-info': typeof HackathonAuthApplicationBasicInfoRoute
  '/$hackathon/application/questionnaire': typeof HackathonAuthApplicationQuestionnaireRoute
  '/$hackathon/application/review': typeof HackathonAuthApplicationReviewRoute
  '/$hackathon/application/rsvp': typeof HackathonAuthApplicationRsvpRoute
  '/$hackathon/application/skills': typeof HackathonAuthApplicationSkillsRoute
  '/$hackathon/application/welcome': typeof HackathonAuthApplicationWelcomeRoute
  '/$hackathon/application': typeof HackathonAuthApplicationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$hackathon': typeof HackathonRouteWithChildren
  '/$hackathon/_auth': typeof HackathonAuthRouteWithChildren
  '/$hackathon/login': typeof HackathonLoginRoute
  '/$hackathon/(account)/rewards': typeof HackathonaccountRewardsRoute
  '/$hackathon/(account)/social-profile': typeof HackathonaccountSocialProfileRoute
  '/$hackathon/(information)/faqs': typeof HackathoninformationFaqsRoute
  '/$hackathon/(information)/hacker-package': typeof HackathoninformationHackerPackageRoute
  '/$hackathon/(information)/schedule': typeof HackathoninformationScheduleRoute
  '/$hackathon/(information)/venue-map': typeof HackathoninformationVenueMapRoute
  '/$hackathon/(account)/': typeof HackathonaccountIndexRoute
  '/$hackathon/_auth/application/basic-info': typeof HackathonAuthApplicationBasicInfoRoute
  '/$hackathon/_auth/application/questionnaire': typeof HackathonAuthApplicationQuestionnaireRoute
  '/$hackathon/_auth/application/review': typeof HackathonAuthApplicationReviewRoute
  '/$hackathon/_auth/application/rsvp': typeof HackathonAuthApplicationRsvpRoute
  '/$hackathon/_auth/application/skills': typeof HackathonAuthApplicationSkillsRoute
  '/$hackathon/_auth/application/welcome': typeof HackathonAuthApplicationWelcomeRoute
  '/$hackathon/_auth/application/': typeof HackathonAuthApplicationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$hackathon'
    | '/$hackathon/login'
    | '/$hackathon/rewards'
    | '/$hackathon/social-profile'
    | '/$hackathon/faqs'
    | '/$hackathon/hacker-package'
    | '/$hackathon/schedule'
    | '/$hackathon/venue-map'
    | '/$hackathon/'
    | '/$hackathon/application/basic-info'
    | '/$hackathon/application/questionnaire'
    | '/$hackathon/application/review'
    | '/$hackathon/application/rsvp'
    | '/$hackathon/application/skills'
    | '/$hackathon/application/welcome'
    | '/$hackathon/application'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$hackathon'
    | '/$hackathon/login'
    | '/$hackathon/rewards'
    | '/$hackathon/social-profile'
    | '/$hackathon/faqs'
    | '/$hackathon/hacker-package'
    | '/$hackathon/schedule'
    | '/$hackathon/venue-map'
    | '/$hackathon/application/basic-info'
    | '/$hackathon/application/questionnaire'
    | '/$hackathon/application/review'
    | '/$hackathon/application/rsvp'
    | '/$hackathon/application/skills'
    | '/$hackathon/application/welcome'
    | '/$hackathon/application'
  id:
    | '__root__'
    | '/'
    | '/$hackathon'
    | '/$hackathon/_auth'
    | '/$hackathon/login'
    | '/$hackathon/(account)/rewards'
    | '/$hackathon/(account)/social-profile'
    | '/$hackathon/(information)/faqs'
    | '/$hackathon/(information)/hacker-package'
    | '/$hackathon/(information)/schedule'
    | '/$hackathon/(information)/venue-map'
    | '/$hackathon/(account)/'
    | '/$hackathon/_auth/application/basic-info'
    | '/$hackathon/_auth/application/questionnaire'
    | '/$hackathon/_auth/application/review'
    | '/$hackathon/_auth/application/rsvp'
    | '/$hackathon/_auth/application/skills'
    | '/$hackathon/_auth/application/welcome'
    | '/$hackathon/_auth/application/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HackathonRoute: typeof HackathonRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HackathonRoute: HackathonRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$hackathon"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$hackathon": {
      "filePath": "$hackathon.tsx",
      "children": [
        "/$hackathon/_auth",
        "/$hackathon/login",
        "/$hackathon/(account)/rewards",
        "/$hackathon/(account)/social-profile",
        "/$hackathon/(information)/faqs",
        "/$hackathon/(information)/hacker-package",
        "/$hackathon/(information)/schedule",
        "/$hackathon/(information)/venue-map",
        "/$hackathon/(account)/"
      ]
    },
    "/$hackathon/_auth": {
      "filePath": "$hackathon/_auth.tsx",
      "parent": "/$hackathon",
      "children": [
        "/$hackathon/_auth/application/basic-info",
        "/$hackathon/_auth/application/questionnaire",
        "/$hackathon/_auth/application/review",
        "/$hackathon/_auth/application/rsvp",
        "/$hackathon/_auth/application/skills",
        "/$hackathon/_auth/application/welcome",
        "/$hackathon/_auth/application/"
      ]
    },
    "/$hackathon/login": {
      "filePath": "$hackathon/login.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(account)/rewards": {
      "filePath": "$hackathon/(account)/rewards.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(account)/social-profile": {
      "filePath": "$hackathon/(account)/social-profile.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(information)/faqs": {
      "filePath": "$hackathon/(information)/faqs.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(information)/hacker-package": {
      "filePath": "$hackathon/(information)/hacker-package.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(information)/schedule": {
      "filePath": "$hackathon/(information)/schedule.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(information)/venue-map": {
      "filePath": "$hackathon/(information)/venue-map.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/(account)/": {
      "filePath": "$hackathon/(account)/index.tsx",
      "parent": "/$hackathon"
    },
    "/$hackathon/_auth/application/basic-info": {
      "filePath": "$hackathon/_auth/application/basic-info.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/questionnaire": {
      "filePath": "$hackathon/_auth/application/questionnaire.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/review": {
      "filePath": "$hackathon/_auth/application/review.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/rsvp": {
      "filePath": "$hackathon/_auth/application/rsvp.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/skills": {
      "filePath": "$hackathon/_auth/application/skills.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/welcome": {
      "filePath": "$hackathon/_auth/application/welcome.tsx",
      "parent": "/$hackathon/_auth"
    },
    "/$hackathon/_auth/application/": {
      "filePath": "$hackathon/_auth/application/index.tsx",
      "parent": "/$hackathon/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
